/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collection721CopySol from "./Collection721 copy.sol";
export type { collection721CopySol };
import type * as collection721OldSol from "./Collection721-old.sol";
export type { collection721OldSol };
import type * as testSol from "./test.sol";
export type { testSol };
export type { Collection1155 } from "./Collection1155";
export type { Collection721 } from "./Collection721";
