version: "3"

services:
  client:
    build:
      context: .
      args:
        - PORT=${PORT:-3001}
    image: gogo-mint-dftsw-2-img
    ports:
      - "80:${PORT:-3001}"
    container_name: gogo-mint-dftsw-2
    restart: always
