version: "3"

services:
  client:
    build:
      context: .
      args:
        - PORT=${PORT:-3001}
    image: gogo-mint-img
    container_name: gogo-mint-dev
    restart: always
networks:
  default:
    external: true
    name: nginx
