/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collection721OldSol from "./Collection721-old.sol";
export type { collection721OldSol };
export type { Collection721 } from "./Collection721";
