/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as collection721CopySol from "./Collection721 copy.sol";
export * as collection721OldSol from "./Collection721-old.sol";
export * as testSol from "./test.sol";
export { Collection1155__factory } from "./Collection1155__factory";
export { Collection721__factory } from "./Collection721__factory";
