/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as collection721OldSol from "./Collection721-old.sol";
export { Collection721__factory } from "./Collection721__factory";
