/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collection1155__factory } from "./Collection1155__factory";
export { Collection721__factory } from "./Collection721__factory";
